### ISSUE TITLE
Need numpy just for sqrt?

### ISSUE THREAD

**Issue by SimonGreenhill** [lingpy/lingpy3#8]
Just spotted this as the [build is failing](https://travis-ci.org/lingpy/lingpy3/jobs/177967118) because  travis isn't installing numpy. I was going to fix this but, it seems that the code so far is only using numpy in [here](https://github.com/lingpy/lingpy3/blob/9d9f68c0e131207f87f1060468b1a0ca2c457fea/lingpy3/algorithm/cython/_misc.py) and just for sqrt. 

There's an implementation of sqrt in the stdlib (``math.sqrt``). Does numpy.sqrt have advantages? is numpy going to be used elsewhere? if not we could remove numpy as a prerequisite?

**Comment by SimonGreenhill** [comment]
And apparently math.sqrt is faster than numpy.sqrt for [scalar floats](http://www.shocksolution.com/2009/01/optimizing-python-code-for-fast-math/).

**Comment by LinguList** [comment]
nope, this is great, I want to get completely rid of numpy, as it is just introducing errors, and now that networkx is also working without numpy, this is even easier. Earlier, in the old wordlist, I had a numpy-array tracking the concepts, but @xrotwang's new construct doesn't have these, so we can finally say bye-bye to numpy for the core behaviour (we might need it, as well as scipy, for other things, but not in the core packages for normal users and normal apps).
